class Settings:
    FETCH_AZURE_DEVICES = True
    FETCH_INTUNE_DEVICES = True
    FETCH_MICROSOFT_DEFENDER_DEVICES = True

    FETCH_All_AZURE_DEVICES = True
    FETCH_All_INTUNE_DEVICES = True

    NUMBER_OF_DEVICES_PAGES_ALLOWED_FOR_FETCHING = 1

    DELETE_OUTDATED_TOPDESK_ASSETS = True
    DEVICES_PER_FETCHED_PAGE = 100 # should be 1000 for lenovo compliance