class Settings:
    FETCH_All_INTUNE_DEVICES = False
    NUMBER_OF_INTUNE_DEVICES_PAGES_ALLOWED_FOR_FETCHING = 10
    DELETE_OUTDATED_TOPDESK_ASSETS = False
    INTUNE_DEVICES_PER_FETCHED_PAGE = 100 # should be 1000 for lenovo compliance